account_number                 = "712390586371"
environment                    = "test"
domain                         = "usp"
opensearch_version             = "OpenSearch_2.7"
instance_count                 = 2
instance_type                  = "r5.xlarge.search"
is_zone_aware                  = true
zone_region_count              = 2
subnet_ids                     = ["subnet-23728345", "subnet-1775b15f"]
security_group_ids             = ["sg-07721ea5677ef6eca"]
total_storage                  = 300
volume_type                    = "gp3"
iops                           = 3000
throughput                     = 593
dedicated_master_enabled       = true
master_instance_count          = 3
master_instance_type           = "t3.medium.search"
node_to_node_encryption        = true
project                        = "USP"
kms_enabled                    = true
encrypt_at_rest_enabled        = true
log_publishing_options_enabled = true
# log_publishing_type            = ["ES_APPLICATION_LOGS", "AUDIT_LOGS"]
