trigger:
  # Batching prevents multiple automated builds for the same branch
  # batch: true
  branches:
    include:
      - develop
      - test
      - staging
      - main

  paths:
    include:
      - apps/lambdas/company-search-criteria-merge/**

pool: Linux-Latest

variables:
  - group: usp-shared-secrets

stages:
  - template: ../azurePipelineTemplates/lambdaTemplate.yml
    parameters:
      AppDir: company-search-criteria-merge
      FunctionName: search-criteria-merge
