const ADDRESS_SIMPLE_VALUE = 'address.simpleValue';

const constants = {
	ADDRESS_CITY_RAW: 'address.city.raw',
	ADDRESS_CITY: 'address.city',
	ADDRESS_COUNTY_RAW: 'address.county.raw',
	ADDRESS_COUNTY: 'address.county',
	ADDRESS_LINE_1_RAW: 'address.line1.raw',
	ADDRESS_LINE_1: 'address.line1',
	ADDRESS_LINE_2_RAW: 'address.line2.raw',
	ADDRESS_LINE_2: 'address.line2',
	ADDRESS_LINE_3_RAW: 'address.line3.raw',
	ADDRESS_LINE_3: 'address.line3',
	ADDRESS_CITY_NGRAM: 'address.city.ngram',
	ADDRESS_POST_CODE: 'address.postCode',
	ADDRESS_POST_CODE_NGRAM: 'address.postCode.ngram',
	ADDRESS_POST_CODE_RAW: 'address.postCode.raw',
	ADDRESS_POST_CODE_WILDCARD: 'address.postCode.*',
	ADDRESS_PROVINCE: 'address.province',
	ADDRESS_SIMPLE_VALUE,
	ADDRESS_STREET: ADDRESS_SIMPLE_VALUE,
	ALTERNATE_NAME: 'alternateName',
	COMPANY_ID: 'companyId',
	COMPANY_NAME_PLAIN: 'companyName.plain',
	COMPANY_NAME_RAW: 'companyName.raw',
	COMPANY_NAME_SYNONYMS: 'companyName.synonyms',
	COMPANY_NAME_WILDCARD: 'companyName.*',
	COMPANY_NAME: 'companyName',
	COMPANY_TYPE: 'companyType',
	CONNECT_ID: 'connectId',
	COUNTRY_CODE_RAW: 'countryCode.raw',
	COUNTRY_CODE: 'countryCode',
	COUNTY: 'county',
	CREDIT_LIMIT: 'creditLimit',
	EMPLOYEES_TO: 'noEmployees.to',
	LEGAL_FORM: 'legalForm',
	LEGAL_GROUP: 'legalGroup',
	NAME_PLAIN: 'name.plain',
	NAME_RAW: 'name.raw',
	NAME_SYNONYMS: 'name.synonyms',
	NAME_WILDCARD: 'name.*',
	NAME: 'name',
	OFFICE_TYPE: 'officeType',
	ORGANIZATION_FORM_DESCRIPTION_EN: 'organizationFormDescriptionEnglish',
	PHONE_NUMBERS: 'phoneNumbers',
	PHONE_NO: 'phoneNo',
	PHONE_NOS: 'phoneNos',
	PHONE_NOS_RAW: 'phoneNos.raw',
	PROVINCE: 'province',
	POSTCODE: 'postCode',
	REG_NUMBER: 'regNumber',
	REG_NO: 'regNo',
	REG_NO_RAW: 'regNo.raw',
	REG_NO_PLAIN: 'regNo.plain',
	REG_TYPE: 'regType',
	SAFE_NO: 'safeNo',
	SHARE_CAPITAL: 'shareCapital',
	STATUS: 'status',
	STATUS_DESCRIPTION: 'statusDescription',
	STATUS_DESCRIPTION_EN: 'statusDescription.en',
	TYPE: 'type',
	TAX_IDS: 'taxIds',
	TRADING_NAMES: 'tradingNames',
	TURNOVER_TO: 'turnover.to',
	VAT_NO: 'vatNo',
	VAT_NO_RAW: 'vatNo.raw',
};

export default constants;
