import constants from '../constants.mjs';

const queryFieldMappings = (inputObj) => {
	const applyIncludePreviousNames = (parsedInputObj, relevantField) => (
		parsedInputObj.includePreviousName ? [relevantField] : []
	);

	const queryFieldMappingsObj = {
		AF: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		AT: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
		},
		BR: {
			address: {
				postCode: {
					default: [constants.ADDRESS_POST_CODE_RAW],
					fallback: [constants.ADDRESS_POST_CODE_RAW],
					plain: [constants.ADDRESS_POST_CODE_RAW],
					synonym: [constants.ADDRESS_POST_CODE_RAW],
					raw: [constants.ADDRESS_POST_CODE_RAW],
					substr: [constants.ADDRESS_POST_CODE_RAW],
				},
			},
		},
		CA: {
			address: {
				simpleValue: {
					default: [constants.ADDRESS_SIMPLE_VALUE],
					fallback: [constants.ADDRESS_SIMPLE_VALUE],
					plain: [constants.ADDRESS_SIMPLE_VALUE],
					synonym: [constants.ADDRESS_SIMPLE_VALUE],
					raw: [constants.ADDRESS_SIMPLE_VALUE],
					substr: [constants.ADDRESS_SIMPLE_VALUE],
				},
				line1: {
					default: [constants.ADDRESS_LINE_1],
					fallback: [constants.ADDRESS_LINE_1],
					plain: [constants.ADDRESS_LINE_1],
					synonym: [constants.ADDRESS_LINE_1_SYNONYMS],
					raw: [constants.ADDRESS_LINE_1_RAW],
					substr: [constants.ADDRESS_LINE_1],
				},
				city: {
					default: [constants.ADDRESS_CITY],
					fallback: [constants.ADDRESS_CITY],
					plain: [constants.ADDRESS_CITY],
					synonym: [constants.ADDRESS_CITY_SYNONYMS],
					raw: [constants.ADDRESS_CITY_RAW],
					substr: [constants.ADDRESS_CITY],
				},
			},
		},
		DE: {
			address: {
				city: {
					default: [constants.ADDRESS_CITY, constants.ADDRESS_REGISTERED_CITY],
					fallback: [constants.ADDRESS_CITY, constants.ADDRESS_REGISTERED_CITY],
					plain: [constants.ADDRESS_CITY, constants.ADDRESS_REGISTERED_CITY],
					synonym: [constants.ADDRESS_CITY_SYNONYMS, constants.ADDRESS_REGISTERED_CITY_SYNONYMS],
					raw: [constants.ADDRESS_CITY_RAW, constants.ADDRESS_REGISTERED_CITY_RAW],
					substr: [constants.ADDRESS_CITY, constants.ADDRESS_REGISTERED_CITY],
				},
			},
			name: {
				default: [constants.NAME, constants.TRADING_NAMES, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES_WILDCARD)],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES_RAW)],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
			},
		},
		FR: {
			address: {
				city: { // Uses synonyms for city
					default: [constants.ADDRESS_CITY],
					fallback: [constants.ADDRESS_CITY],
					plain: [constants.ADDRESS_CITY],
					synonym: [constants.ADDRESS_CITY_SYNONYMS],
					raw: [constants.ADDRESS_CITY_RAW],
					substr: [constants.ADDRESS_CITY],
				},
			},
			name: {
				default: [constants.ALTERNATE_NAME_PLAIN],
				fallback: [constants.ALTERNATE_NAME_WILDCARD],
				plain: [constants.ALTERNATE_NAME_PLAIN],
				synonym: [constants.ALTERNATE_NAME_SYNONYMS],
				raw: [constants.ALTERNATE_NAME_RAW, constants.ACRONYM],
				substr: [constants.ALTERNATE_NAME_PLAIN],
			},
		},
		GB: {
			name: {
				default: [constants.NAME, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				fallback: [constants.NAME_WILDCARD, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES_WILDCARD)],
				plain: [constants.NAME_PLAIN, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				synonym: [constants.NAME_SYNONYMS, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
				raw: [constants.NAME_RAW, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES_RAW)],
				substr: [constants.NAME_PLAIN, ...applyIncludePreviousNames(inputObj, constants.PREVIOUS_NAMES)],
			},
		},
		IE: {
			address: {
				county: {
					default: [constants.ADDRESS_COUNTY],
					fallback: [constants.ADDRESS_COUNTY],
					plain: [constants.ADDRESS_COUNTY],
					synonym: [constants.ADDRESS_COUNTY],
					raw: [constants.ADDRESS_COUNTY_RAW],
					substr: [constants.ADDRESS_COUNTY],
				},
			},
		},
		KH: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		LU: {
			name: {
				default: [constants.NAME, constants.PREVIOUS_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.PREVIOUS_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.PREVIOUS_NAMES],
				synonym: [constants.NAME_SYNONYMS, constants.PREVIOUS_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.PREVIOUS_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.PREVIOUS_NAMES],
			},
		},
		MM: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		MY: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		NO: {
			address: {
				city: { // Uses synonyms for city
					default: [constants.ADDRESS_CITY],
					fallback: [constants.ADDRESS_CITY],
					plain: [constants.ADDRESS_CITY],
					synonym: [constants.ADDRESS_CITY_SYNONYMS],
					raw: [constants.ADDRESS_CITY_RAW],
					substr: [constants.ADDRESS_CITY],
				},
			},
			tradingNames: { // Uses raw for trading names
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		SE: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
		},
		TH: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		VN: {
			name: {
				default: [constants.NAME, constants.TRADING_NAMES],
				fallback: [constants.NAME_WILDCARD, constants.TRADING_NAMES_WILDCARD],
				plain: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
				synonym: [constants.NAME_SYNONYMS, constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.NAME_RAW, constants.TRADING_NAMES_RAW],
				substr: [constants.NAME_PLAIN, constants.TRADING_NAMES_PLAIN],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES_SYNONYMS],
				raw: [constants.TRADING_NAMES_RAW],
				substr: [constants.TRADING_NAMES],
			},
		},
		default: {
			acronym: {
				default: [constants.ACRONYM],
				fallback: [constants.ACRONYM],
				plain: [constants.ACRONYM],
				synonym: [constants.ACRONYM],
				raw: [constants.ACRONYM],
				substr: [constants.ACRONYM],
			},
			activityCodes: {
				default: [constants.ACTIVITY_CODES],
				fallback: [constants.ACTIVITY_CODES],
				plain: [constants.ACTIVITY_CODES],
				synonym: [constants.ACTIVITY_CODES],
				raw: [constants.ACTIVITY_CODES],
				substr: [constants.ACTIVITY_CODES],
			},
			address: {
				simpleValue: {
					default: [constants.ADDRESS_SIMPLE_VALUE],
					fallback: [constants.ADDRESS_SIMPLE_VALUE],
					plain: [constants.ADDRESS_SIMPLE_VALUE],
					synonym: [constants.ADDRESS_SIMPLE_VALUE],
					raw: [constants.ADDRESS_SIMPLE_VALUE_KEYWORD],
					substr: [constants.ADDRESS_SIMPLE_VALUE],
				},
				line1: {
					default: [constants.ADDRESS_LINE_1],
					fallback: [constants.ADDRESS_LINE_1],
					plain: [constants.ADDRESS_LINE_1],
					synonym: [constants.ADDRESS_LINE_1],
					raw: [constants.ADDRESS_LINE_1_RAW],
					substr: [constants.ADDRESS_LINE_1],
				},
				houseNo: {
					default: [constants.ADDRESS_HOUSE_NUMBER],
					fallback: [constants.ADDRESS_HOUSE_NUMBER],
					plain: [constants.ADDRESS_HOUSE_NUMBER],
					synonym: [constants.ADDRESS_HOUSE_NUMBER],
					raw: [constants.ADDRESS_HOUSE_NUMBER],
					substr: [constants.ADDRESS_HOUSE_NUMBER],
				},
				street: {
					default: [constants.ADDRESS_STREET],
					fallback: [constants.ADDRESS_STREET],
					plain: [constants.ADDRESS_STREET],
					synonym: [constants.ADDRESS_STREET_SYNONYMS],
					raw: [constants.ADDRESS_STREET_RAW],
					substr: [constants.ADDRESS_STREET],
				},
				line2: {
					default: [constants.ADDRESS_LINE_2],
					fallback: [constants.ADDRESS_LINE_2],
					plain: [constants.ADDRESS_LINE_2],
					synonym: [constants.ADDRESS_LINE_2],
					raw: [constants.ADDRESS_LINE_2_RAW],
					substr: [constants.ADDRESS_LINE_2],
				},
				line3: {
					default: [constants.ADDRESS_LINE_3],
					fallback: [constants.ADDRESS_LINE_3],
					plain: [constants.ADDRESS_LINE_3],
					synonym: [constants.ADDRESS_LINE_3],
					raw: [constants.ADDRESS_LINE_3_RAW],
					substr: [constants.ADDRESS_LINE_3],
				},
				city: {
					default: [constants.ADDRESS_CITY],
					fallback: [constants.ADDRESS_CITY],
					plain: [constants.ADDRESS_CITY],
					synonym: [constants.ADDRESS_CITY],
					raw: [constants.ADDRESS_CITY_RAW],
					substr: [constants.ADDRESS_CITY],
				},
				country: {
					default: [constants.ADDRESS_COUNTRY],
					fallback: [constants.ADDRESS_COUNTRY],
					plain: [constants.ADDRESS_COUNTRY],
					synonym: [constants.ADDRESS_COUNTRY],
					raw: [constants.ADDRESS_COUNTRY_RAW],
					substr: [constants.ADDRESS_COUNTRY],
				},
				province: {
					default: [constants.ADDRESS_PROVINCE],
					fallback: [constants.ADDRESS_PROVINCE],
					plain: [constants.ADDRESS_PROVINCE],
					synonym: [constants.ADDRESS_PROVINCE],
					raw: [constants.ADDRESS_PROVINCE_RAW],
					substr: [constants.ADDRESS_PROVINCE],
				},
				postCode: {
					default: [constants.ADDRESS_POST_CODE],
					fallback: [constants.ADDRESS_POST_CODE_WILDCARD],
					plain: [constants.ADDRESS_POST_CODE],
					synonym: [constants.ADDRESS_POST_CODE],
					raw: [constants.ADDRESS_POST_CODE_RAW],
					substr: [constants.ADDRESS_POST_CODE_NGRAM],
				},
				telephone: {
					default: [constants.ADDRESS_TELEPHONE],
					fallback: [constants.ADDRESS_TELEPHONE],
					plain: [constants.ADDRESS_TELEPHONE],
					synonym: [constants.ADDRESS_TELEPHONE],
					raw: [constants.ADDRESS_TELEPHONE_RAW],
					substr: [constants.ADDRESS_TELEPHONE],
				},
			},
			companyType: {
				default: [constants.COMPANY_TYPE],
				fallback: [constants.COMPANY_TYPE],
				plain: [constants.COMPANY_TYPE],
				synonym: [constants.COMPANY_TYPE],
				raw: [constants.COMPANY_TYPE],
				substr: [constants.COMPANY_TYPE],
			},
			name: {
				default: [constants.NAME],
				fallback: [constants.NAME_WILDCARD],
				plain: [constants.NAME_PLAIN],
				synonym: [constants.NAME_SYNONYMS],
				raw: [constants.NAME_RAW],
				substr: [constants.NAME_PLAIN],
			},
			phoneNo: {
				default: [constants.PHONE_NUMBERS_RAW],
				fallback: [constants.PHONE_NUMBERS_RAW],
				plain: [constants.PHONE_NUMBERS_RAW],
				synonym: [constants.PHONE_NUMBERS_RAW],
				raw: [constants.PHONE_NUMBERS_RAW],
				substr: [constants.PHONE_NUMBERS_RAW],
			},
			phoneNos: {
				default: [constants.PHONE_NOS],
				fallback: [constants.PHONE_NOS],
				plain: [constants.PHONE_NOS],
				synonym: [constants.PHONE_NOS],
				raw: [constants.PHONE_NOS_RAW],
				substr: [constants.PHONE_NOS],
			},
			phoneNumbers: {
				default: [constants.PHONE_NUMBERS],
				fallback: [constants.PHONE_NUMBERS],
				plain: [constants.PHONE_NUMBERS],
				synonym: [constants.PHONE_NUMBERS],
				raw: [constants.PHONE_NUMBERS_RAW],
				substr: [constants.PHONE_NUMBERS],
			},
			regNo: {
				default: [constants.REG_NO],
				fallback: [constants.REG_NO],
				plain: [constants.REG_NO],
				synonym: [constants.REG_NO],
				raw: [constants.REG_NO],
				substr: [constants.REG_NO],
			},
			regType: {
				default: [constants.REG_TYPE],
				fallback: [constants.REG_TYPE],
				plain: [constants.REG_TYPE],
				synonym: [constants.REG_TYPE],
				raw: [constants.REG_TYPE],
				substr: [constants.REG_TYPE],
			},
			tradingNames: {
				default: [constants.TRADING_NAMES],
				fallback: [constants.TRADING_NAMES],
				plain: [constants.TRADING_NAMES],
				synonym: [constants.TRADING_NAMES],
				raw: [constants.TRADING_NAMES],
				substr: [constants.TRADING_NAMES],
			},
		},
	};

	return queryFieldMappingsObj;
};

export default queryFieldMappings;
