trigger:
  # Batching prevents multiple automated builds for the same branch
  # batch: true
  branches:
    include:
      - develop
      - test
      - staging
      - main

  paths:
    include:
      - apps/lambdas/search-criterias/**
      - apps/core/config/**

pool: Linux-Latest

variables:
  - group: usp-shared-secrets

stages:
  - template: ../azurePipelineTemplates/lambdaTemplate.yml
    parameters:
      AppDir: search-criterias
      FunctionName: search-criteria
