select
  "activityCodes",
  "address.city",
  "address.county",
  "address.line1",
  "address.line2",
  "address.line3",
  "address.postalCode",
  "companyId",
  "companyName",
  "countryCode",
  "creditLimit",
  TO_CHAR(cast("incorporationDate" as timestamp), 'YYYY-MM-DD"T"HH24:MI:SS.FF"Z"') as "incorporationDate",
  TO_CHAR(cast("lastAccountsDate" as timestamp), 'YYYY-MM-DD"T"HH24:MI:SS.FF"Z"') as "lastAccountsDate",
  "lastUpdateDate",
  "legalForm",
  "noEmployees.from",
  "noEmployees.to",
  "officeType",
  "phoneNumbers",
  "preTaxProfit",
  "previousNames",
  "regNumber",
  "regType",
  "riskRating",
  "riskScore",
  "status",
  "statusDescription",
  "taxIds",
  "tpsFlag",
  "turnover.from",
  "turnover.to",
  "urls"
from v_company_search